pipline_test:
  stage: .pre
  tags:
    - ci
  script:
    - echo "Pipline Works!!"

build:
  tags:
    - ci
  stage: build
  script:
    - make
  artifacts:
    paths:
      - hello
    expire_in: 1 week