include: 'https://raw.githubusercontent.com/Nitrokey/common-ci-jobs/master/common_jobs.yml'

stages:
  - pull-github
  - build
  - deploy


variables:
  #Repo for shared scripts (pull.sh release.sh, nightly_upload.sh):
  GIT_STRATEGY: clone     
  GIT_DEPTH: 0         
  GIT_SUBMODULE_STRATEGY: recursive
  SCRIPTS_REPO: git@git.dotplex.com:nitrokey/gitlab-ci.git
  REPO_USER: nitrokey
  REPO_NAME: nitrokey-app
  MAIN_BRANCH: master
  COMMON_PULL: "true"
  COMMON_UPLOAD_NIGHTLY: "true"
  COMMON_GITHUB_RELEASE: "true"
  COMMON_UPLOAD_FILES: "false"


#hello-ubuntu:
#  stage: .pre
#  script:
#    - echo "Hello Ubuntu"
#    - lsb_release -a
#  tags:
#    - docker

hello-mac:
  stage: .pre
  script:
    - echo "Hello Mac"
    - system_profiler SPSoftwareDataType
  tags:
    - macos

mac-build-artifacts:
  stage: build
  tags:
    - macos
  script:
    - make
  artifacts:
    paths:
      - hello