image: docker:latest

services:
  - docker:dind

build:
  stage: build
  script:
    - docker build -t test .


#pipline_test:
#  stage: .pre
#  script:
#    - echo "Pipline Works!!"
#
#build:
#  stage: build
#  script:
#    - apt-get update && apt-get install make
#    - apt-get install -y gcc
#    - make
#  artifacts:
#    paths:
#      - hello
#    expire_in: 1 week
# do it