demo_job_1:
  stage: .pre
  tags:
    - ci
  script:
    - echo "Hello, world"

build:
  tags:
    - ci
  stage: build
  script:
    - make
  artifacts:
    paths:
      - hellow
    expire_in: 1 week