hello-ubuntu:
  stage: .pre
  script:
    - echo "Hello Ubuntu"
    - lsb_release -a
  tags:
    - docker

hello-mac:
  stage: .pre
  script:
    - echo "Hello Mac"
    - system_profiler SPSoftwareDataType
  tags:
    - macos

mac-build-artifacts:
  stage: build
  tags:
    - macos
  script:
    - make
  artifacts:
    paths:
      - hello
    expire_in: 1 week